### ISSUE TITLE
Support for recently updated dependencies, Phoenix 1.4, Elixir 1.7.x

### ISSUE THREAD

**Issue by scott-wyatt** [api-hogs/bureaucrat#45]
#### Description
2 Parts

Part 1:

It appears that Bureaucrat works as expected in the Elixir 1.7.x environment, however it throws a warning if above Elixir 1.6. Would you like a PR for adding Elixir 1.7 testing?

Part 2:

Is there a Roadmap to support Phoenix 1.4? It seems like Bureaucrat should still work with 1.4 as long as the default path is changed. Would you like a PR for adding Phoenix 1.4 testing and/or accept a new default path proposal?

#### Links
[Elixir Semantic Versioning](https://hexdocs.pm/elixir/Version.html)
[Phoenix Versioning](https://github.com/phoenixframework/phoenix/releases)

#### Related Issues: 
#41 #22 

#### Edit
It may also be a good idea to switch the default JSON parser to Jason as Phoenix 1.4 now uses this as a default.

**Comment by OpakAlex** [comment]
Hello @scott-wyatt, adding some tests so good idea. But i don't use this project a lot now, and i don't use new version of elixir and phoenix (because they comes only for money, and nothing more). I freeze versions which is good for me, and don't care about new updates shit. If you want you can do PR's, and i will merge them. But i don't want spent my time, for updates,which is free, and in same time phoenixframework chanrge 300 per hour just for consulting their updates. This is my position.

**Comment by scott-wyatt** [comment]
@OpakAlex fair enough.  I'll probably submit some PRs and thanks in advanced for taking care of the merging. I've seen this project mentioned in quite a few Elixir books and it would be a shame to deprecate it if it's still useful to some. 

P>S> $300 an hour?! And I thought my prices were high haha.

**Comment by OpakAlex** [comment]
Haha, but all this changes not make sense, really, and new project i will start in pure cowboy web server with erlang, no more elixir for me. It's like buy new iphone every year, stupid, and just for produce rubish in ocean.
