### ISSUE TITLE
Not able to use with umbrella app with multiple .md output files

### ISSUE THREAD

**Issue by EskiMag** [api-hogs/bureaucrat#49]
I am using Bureaucrat to generate my API docs for one of my apps inside the umbrella project. So far so good. I decided to use it to generate API docs for another app inside the same umbrella with a separate Markdown output file. But after doing this, I got somehow mixed results. File for app2 is OK, but file for app1 contains records from app1 and app2 combined. I guess it's because of `Bureaucrat.Recorder` is being used as a singleton basically.
Do you have any idea if there's a simple workaround available? It's not a requirement to have API docs in an output file per app, but I need to have a clear separation of which API docs are related to which app.
Thanks a lot. :-)

**Comment by OpakAlex** [comment]
Hello @EskiMag, we don't support umbrella apps. But if you have time, you can look and try to change. As i told into prev issues, we don't want to support new features or new releases Elixir / Phoenix, because we think Elixir killing Erlang ideas and infrastructures. For ourself we migrating to erlang and poor cowboy servers.

**Comment by EskiMag** [comment]
OK, thanks a lot for your response. I'll take a look at it.
